# Program Definitions
# See https://wiki.hyprland.org/Configuring/Keywords/

# Set default programs
$terminal = kitty
$menu = wofi --show drun

# Modifier keys
$mainMod = SUPER
$shiftMod = SHIFT
$SUPER_SHIFT = SUPER_SHIFT
