[ids]
*
[global]
chord_timeout = 50
layer_indicator = 0
[main]

f+j = esc
capslock = overload(meta, esc)
#tab= overload(mytab, tab)
#[ = overloadt2(mytab, [,200)
' = overloadt2(meta, ', 200)
esc = capslock
space = overloadt(parkour, space, 200)

[mytab]
space = C-right


[parkour]
h = left
j = down
k = up
l = right
w = C-right
b = C-left
a = home
d = end
i = enter
; = backspace
n = S-left
p = S-right
s = ~
v = /
