general {
  gaps_in = 5
    gaps_out = 4
    border_size = 2

# Border colors
    col.active_border = rgba(245,245,245,1) rgba(0,0,0,0.2) 45deg
    col.inactive_border = rgba(0,0,0,0.2)

    resize_on_border = false
    allow_tearing = false
# layout = dwindle
    layout = master
}
# Window decoration

decoration {
  rounding = 1 
    rounding_power = 2

# Window opacity
    active_opacity = 1.0
    inactive_opacity = 1.0

# Shadow settings
    shadow {
      enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

# Blur settings
  blur {
    enabled = true
      size = 5
      passes = 3
      xray = true
      new_optimizations = true
  }
}
