#!/usr/bin/env bash
preload = /home/cj/Downloads/Wallpapers/2.jpg
preload = ~/Downloads/Wallpapers/3.jpg
preload = ~/Downloads/Wallpapers/13.jpeg
preload = ~/Downloads/Wallpapers/1.jpg
preload = ~/Downloads/Wallpapers/4.jpg
ipc = true
wallpaper = eDP-1,/home/cj/Downloads/Wallpapers/4.jpg
wallpaper = HDMI-A-1,/home/cj/Downloads/Wallpapers/13.jpeg
