# Main Hyprland Configuration
# https://wiki.hyprland.org/Configuring/

# Source external configuration files
source = ~/.config/hypr/hyprHelper/monitors.conf
source = ~/.config/hypr/hyprHelper/programs.conf
source = ~/.config/hypr/hyprHelper/autostart.conf
source = ~/.config/hypr/hyprHelper/environment.conf
source = ~/.config/hypr/hyprHelper/appearance.conf
source = ~/.config/hypr/hyprHelper/input.conf
source = ~/.config/hypr/hyprHelper/keybinds.conf
source = ~/.config/hypr/hyprHelper/windowrule.conf
source = ~/.config/hypr/hyprHelper/workspaces.conf

# Basic wallpaper setup
# exec-once = hyprpaper

# Enable debug logging
debug {
    disable_logs = false
}
